; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = attiny13a

[env]
framework = arduino

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new

[env:attiny13a]
platform = atmelavr
board = attiny13a

; You must first flash the right bootloader using the Arduino IDE.
; Board manager URL: https://mcudude.github.io/MicroCore/package_MCUdude_MicroCore_index.json
; You must use the Arduino IDE MicroCore version <= 2.4.0: https://github.com/MCUdude/MicroCore/issues/174
board_build.f_cpu = 9600000L
monitor_speed = 115200

upload_port = COM6
monitor_port = COM12

; Arduino as ISP.
upload_protocol = stk500v1
upload_flags = -b19200

; #include <core_settings.h>
; In this file you can find MicroCore configurations.
build_flags =
	-D CUSTOM_BAUD_RATE=${env.monitor_speed}
	-D PWM_PRESCALER_64
